import { writeFileSync, readFileSync } from 'node:fs';
import { ROUTES } from './routes.js';

const target = new URL('../../../packages/api-types/src/index.js', import.meta.url);
const prev = readFileSync(target, 'utf8');
const version = String(Number(prev.match(/SCHEMA_VERSION = '(\d+)'/)?.[1] ?? 0) + 1);
writeFileSync(
  target,
  `// GENERATED by \`pnpm --filter @acme/api run codegen\`. Do not edit by hand.\n` +
    `export const SCHEMA_VERSION = '${version}';\n` +
    `export const ROUTES = ${JSON.stringify(ROUTES)};\n`,
);
process.stdout.write(`api-types regenerated at schema ${version}\n`);
